// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfdseztpkzabwamlrgpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZHNlenRwa3phYndhbWxyZ3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTI4MzgsImV4cCI6MjA2MTg4ODgzOH0.j1C_1pdjvbMlaWgiD6izUAK34WaPG7koPhnGcKAKeLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);